type = "web_pixel_extension"
name = "analytics-pixel"
runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.webhookUrl]
name = "Webhook URL"
description = "Your server endpoint to receive events"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]

[settings.fields.shopName]
name = "Shop Name"
description = "Identifier for your shop"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]
