# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "181a611e074aaa1904c7ed0b88ce4952"
name = "pixel-extension-app"
application_url = "http://localhost:3000/v1/integrations/shopify/install"
embedded = false
handle = "pixel-extension-app"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_reports,read_customers,read_themes,write_themes,read_cart_transforms,read_checkouts,read_orders,write_pixels,read_customer_events"

[auth]
redirect_urls = ["http://localhost:3000/v1/integrations/shopify/callback"]

[pos]
embedded = false
